<?php

namespace Database\Seeders;

use App\Models\TaxaEntrega;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TaxaDeEntregaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('taxa_entregas')->insert([
            ['bairro' => 'Abadia', 'preco' => ''],
            ['bairro' => 'Alfredo Freire II', 'preco' => ''],
            ['bairro' => 'Alfredo Freire III', 'preco' => ''],
            ['bairro' => 'Amoroso Costa', 'preco' => ''],
            ['bairro' => 'Antônia Cândida I', 'preco' => ''],
            ['bairro' => 'Beija-Flor', 'preco' => ''],
            ['bairro' => 'Beija-Flor II', 'preco' => ''],
            ['bairro' => 'Bela Vista', 'preco' => ''],
            ['bairro' => 'Boa Vista', 'preco' => ''],
            ['bairro' => 'Bom Retiro', 'preco' => ''],
            ['bairro' => 'Capelinha do Barreiro', 'preco' => ''],
            ['bairro' => 'Centro', 'preco' => ''],
            ['bairro' => 'Cidade Jardim', 'preco' => ''],
            ['bairro' => 'Cidade Nova', 'preco' => ''],
            ['bairro' => 'Cidade Ozanan', 'preco' => ''],
            ['bairro' => 'COHAB Boa Vista', 'preco' => ''],
            ['bairro' => 'Conjunto Alfredo Freire', 'preco' => ''],
            ['bairro' => 'Conjunto Antônio Barbosa de Souza', 'preco' => ''],
            ['bairro' => 'Conjunto Cássio Rezende', 'preco' => ''],
            ['bairro' => 'Conjunto Chica Ferreira', 'preco' => ''],
            ['bairro' => 'Conjunto Costa Telles I', 'preco' => ''],
            ['bairro' => 'Conjunto Costa Telles II', 'preco' => ''],
            ['bairro' => 'Conjunto Frei Eugênio', 'preco' => ''],
            ['bairro' => 'Conjunto Guanabara', 'preco' => ''],
            ['bairro' => 'Conjunto José Barbosa', 'preco' => ''],
            ['bairro' => 'Conjunto José Vallim de Melo', 'preco' => ''],
            ['bairro' => 'Conjunto Manoel Mendes', 'preco' => ''],
            ['bairro' => 'Conjunto Margarida Rosa de Azevedo', 'preco' => ''],
            ['bairro' => 'Conjunto Maringá I', 'preco' => ''],
            ['bairro' => 'Conjunto Maringá II', 'preco' => ''],
            ['bairro' => 'Conjunto Morada do Sol', 'preco' => ''],
            ['bairro' => 'Conjunto Pontal', 'preco' => ''],
            ['bairro' => 'Conjunto Sete Colinas', 'preco' => ''],
            ['bairro' => 'Conjunto Treze de Maio', 'preco' => ''],
            ['bairro' => 'Conjunto Uberaba', 'preco' => ''],
            ['bairro' => 'Conjunto Umuarama', 'preco' => ''],
            ['bairro' => 'Conquistinha', 'preco' => ''],
            ['bairro' => 'Cyrela Landscape', 'preco' => ''],
            ['bairro' => 'Damha Residencial Uberaba I', 'preco' => ''],
            ['bairro' => 'Damha Residencial Uberaba II', 'preco' => ''],
            ['bairro' => 'Deolinda Freire', 'preco' => ''],
            ['bairro' => 'Deolinda Laura', 'preco' => ''],
            ['bairro' => 'Distrito Industrial I', 'preco' => ''],
            ['bairro' => 'Distrito Industrial II', 'preco' => ''],
            ['bairro' => 'Distrito Industrial III', 'preco' => ''],
            ['bairro' => 'Distrito Industrial IV', 'preco' => ''],
            ['bairro' => 'Dom Eduardo', 'preco' => ''],
            ['bairro' => 'Estados Unidos', 'preco' => ''],
            ['bairro' => 'Estância dos Ipês', 'preco' => ''],
            ['bairro' => 'Estrela da Vitória', 'preco' => ''],
            ['bairro' => 'Europark', 'preco' => ''],
            ['bairro' => 'Fabrício', 'preco' => ''],
            ['bairro' => 'Flamboyant Residencial Park', 'preco' => ''],
            ['bairro' => 'Gleba Déa Maria', 'preco' => ''],
            ['bairro' => 'Gleba Santa Mônica', 'preco' => ''],
            ['bairro' => 'Grande Horizonte', 'preco' => ''],
            ['bairro' => 'Indianópolis', 'preco' => ''],
            ['bairro' => 'Irmãos Soares', 'preco' => ''],
            ['bairro' => 'Jardim Alexandre Campos', 'preco' => ''],
            ['bairro' => 'Jardim Alvorada', 'preco' => ''],
            ['bairro' => 'Jardim Amélia', 'preco' => ''],
            ['bairro' => 'Jardim América', 'preco' => ''],
            ['bairro' => 'Jardim Aquárius', 'preco' => ''],
            ['bairro' => 'Jardim Belo Horizonte', 'preco' => ''],
            ['bairro' => 'Jardim Bento de Assis Valim', 'preco' => ''],
            ['bairro' => 'Jardim Brasília', 'preco' => ''],
            ['bairro' => 'Jardim Califórnia', 'preco' => ''],
            ['bairro' => 'Jardim Canadá', 'preco' => ''],
            ['bairro' => 'Jardim Copacabana', 'preco' => ''],
            ['bairro' => 'Jardim do Lago', 'preco' => ''],
            ['bairro' => 'Jardim Eldorado', 'preco' => ''],
            ['bairro' => 'Jardim Elza Amuí I', 'preco' => ''],
            ['bairro' => 'Jardim Elza Amuí II', 'preco' => ''],
            ['bairro' => 'Jardim Elza Amuí III', 'preco' => ''],
            ['bairro' => 'Jardim Elza Amuí IV', 'preco' => ''],
            ['bairro' => 'Jardim Espanha', 'preco' => ''],
            ['bairro' => 'Jardim Espírito Santo', 'preco' => ''],
            ['bairro' => 'Jardim Esplanada', 'preco' => ''],
            ['bairro' => 'Jardim Imperador', 'preco' => ''],
            ['bairro' => 'Jardim Induberaba', 'preco' => ''],
            ['bairro' => 'Jardim Itália', 'preco' => ''],
            ['bairro' => 'Jardim Itália II', 'preco' => ''],
            ['bairro' => 'Jardim Maracanã', 'preco' => ''],
            ['bairro' => 'Jardim Maria Alice', 'preco' => ''],
            ['bairro' => 'Jardim Metrópole', 'preco' => ''],
            ['bairro' => 'Jardim Nenê Gomes', 'preco' => ''],
            ['bairro' => 'Jardim Primavera', 'preco' => ''],
            ['bairro' => 'Jardim Santa Clara', 'preco' => ''],
            ['bairro' => 'Jardim Santa Inez', 'preco' => ''],
            ['bairro' => 'Jardim São Bento', 'preco' => ''],
            ['bairro' => 'Jardim Terra Santa', 'preco' => ''],
            ['bairro' => 'Jardim Triângulo', 'preco' => ''],
            ['bairro' => 'Jardim Uberaba', 'preco' => ''],
            ['bairro' => 'Jockey Park', 'preco' => ''],
            ['bairro' => 'Josa Bernardino I', 'preco' => ''],
            ['bairro' => 'Josa Bernardino II', 'preco' => ''],
            ['bairro' => 'Leblon', 'preco' => ''],
            ['bairro' => 'Loteamento Craide', 'preco' => ''],
            ['bairro' => 'Loteamento das Américas', 'preco' => ''],
            ['bairro' => 'Loteamento das Gameleiras', 'preco' => ''],
            ['bairro' => 'Loteamento Guilherme Borges', 'preco' => ''],
            ['bairro' => 'Loteamento Jardim Santa Clara', 'preco' => ''],
            ['bairro' => 'Loteamento Petrópolis', 'preco' => ''],
            ['bairro' => 'Loteamento Residencial Cândida Borges', 'preco' => ''],
            ['bairro' => 'Lourdes', 'preco' => ''],
            ['bairro' => 'Mangueiras', 'preco' => ''],
            ['bairro' => 'Manhattan', 'preco' => ''],
            ['bairro' => 'Maria Alice', 'preco' => ''],
            ['bairro' => 'Mercês', 'preco' => ''],
            ['bairro' => 'Mônica Cristina', 'preco' => ''],
            ['bairro' => 'Morada das Fontes', 'preco' => ''],
            ['bairro' => 'Nossa Senhora da Abadia', 'preco' => ''],
            ['bairro' => 'Novo Horizonte', 'preco' => ''],
            ['bairro' => 'Núcleo Habitacional Silvério Cartafina', 'preco' => ''],
            ['bairro' => 'Núcleo Residencial Tutunas', 'preco' => ''],
            ['bairro' => 'Olinda', 'preco' => ''],
            ['bairro' => 'Oneida Mendes', 'preco' => ''],
            ['bairro' => 'Pacaembu', 'preco' => ''],
            ['bairro' => 'Pacaembu II', 'preco' => ''],
            ['bairro' => 'Parque Colibri', 'preco' => ''],
            ['bairro' => 'Parque das Américas', 'preco' => ''],
            ['bairro' => 'Parque das Gameleiras', 'preco' => ''],
            ['bairro' => 'Parque das Laranjeiras', 'preco' => ''],
            ['bairro' => 'Parque do Café', 'preco' => ''],
            ['bairro' => 'Parque do Mirante', 'preco' => ''],
            ['bairro' => 'Parque dos Buritis', 'preco' => ''],
            ['bairro' => 'Parque dos Girassóis', 'preco' => ''],
            ['bairro' => 'Parque dos Ipês', 'preco' => ''],
            ['bairro' => 'Parque Exposição', 'preco' => ''],
            ['bairro' => 'Parque Hiléia', 'preco' => ''],
            ['bairro' => 'Parque São Geraldo', 'preco' => ''],
            ['bairro' => 'Peirópolis', 'preco' => ''],
            ['bairro' => 'Planalto', 'preco' => ''],
            ['bairro' => 'Ponte Alta', 'preco' => ''],
            ['bairro' => 'Portal Beija Flor', 'preco' => ''],
            ['bairro' => 'Portal do Sol', 'preco' => ''],
            ['bairro' => 'Princesa do Sertão', 'preco' => ''],
            ['bairro' => 'Quinta Boa Esperança', 'preco' => ''],
            ['bairro' => 'Recanto da Terra', 'preco' => ''],
            ['bairro' => 'Recanto das Flores', 'preco' => ''],
            ['bairro' => 'Recanto das Torres', 'preco' => ''],
            ['bairro' => 'Recanto do Sol', 'preco' => ''],
            ['bairro' => 'Recreio dos Bandeirantes', 'preco' => ''],
            ['bairro' => 'Residencial 2000', 'preco' => ''],
            ['bairro' => 'Residencial Alves Valim', 'preco' => ''],
            ['bairro' => 'Residencial Anita', 'preco' => ''],
            ['bairro' => 'Residencial Budeus', 'preco' => ''],
            ['bairro' => 'Residencial Doutor Abel Reis', 'preco' => ''],
            ['bairro' => 'Residencial Estados Unidos', 'preco' => ''],
            ['bairro' => 'Residencial Jardim Anatê I', 'preco' => ''],
            ['bairro' => 'Residencial Jardim Anatê II', 'preco' => ''],
            ['bairro' => 'Residencial Mário de Almeida Franco', 'preco' => ''],
            ['bairro' => 'Residencial Monte Castelo', 'preco' => ''],
            ['bairro' => 'Residencial Morada Du Park', 'preco' => ''],
            ['bairro' => 'Residencial Morumbi', 'preco' => ''],
            ['bairro' => 'Residencial Nova Era', 'preco' => ''],
            ['bairro' => 'Residencial Palmeiras', 'preco' => ''],
            ['bairro' => 'Residencial Paulo Cury', 'preco' => ''],
            ['bairro' => 'Residencial Presidente Tancredo Neves', 'preco' => ''],
            ['bairro' => 'Residencial Rio de Janeiro', 'preco' => ''],
            ['bairro' => 'Residencial Sebastião Rezende Braga', 'preco' => ''],
            ['bairro' => 'Residencial Terra Nova', 'preco' => ''],
            ['bairro' => 'Residencial Veneza', 'preco' => ''],
            ['bairro' => 'Santa Fé', 'preco' => ''],
            ['bairro' => 'Santa Maria', 'preco' => ''],
            ['bairro' => 'Santa Marta', 'preco' => ''],
            ['bairro' => 'Santa Rosa', 'preco' => ''],
            ['bairro' => 'Santos Dumont', 'preco' => ''],
            ['bairro' => 'São Benedito', 'preco' => ''],
            ['bairro' => 'São José', 'preco' => ''],
            ['bairro' => 'São Sebastião', 'preco' => ''],
            ['bairro' => 'Seriema', 'preco' => ''],
            ['bairro' => 'Serra do Sol', 'preco' => ''],
            ['bairro' => 'Serra Dourada', 'preco' => ''],
            ['bairro' => 'Tiago e Jéssica', 'preco' => ''],
            ['bairro' => 'Tita Rezende', 'preco' => ''],
            ['bairro' => 'Unidade de Planejamento e Gestão Urbana Portal', 'preco' => ''],
            ['bairro' => 'Univerdecidade', 'preco' => ''],
            ['bairro' => 'Universitário', 'preco' => ''],
            ['bairro' => 'Vale do Sol', 'preco' => ''],
            ['bairro' => 'Vila Alvorada', 'preco' => ''],
            ['bairro' => 'Vila Arquelau', 'preco' => ''],
            ['bairro' => 'Vila Boa Vista', 'preco' => ''],
            ['bairro' => 'Vila Celeste', 'preco' => ''],
            ['bairro' => 'Vila Ceres', 'preco' => ''],
            ['bairro' => 'Vila Craide', 'preco' => ''],
            ['bairro' => 'Vila Esperança', 'preco' => ''],
            ['bairro' => 'Vila Frei Eugênio', 'preco' => ''],
            ['bairro' => 'Vila Maria Helena', 'preco' => ''],
            ['bairro' => 'Vila Militar', 'preco' => ''],
            ['bairro' => 'Vila Nossa Senhora Aparecida', 'preco' => ''],
            ['bairro' => 'Vila Olímpica', 'preco' => ''],
            ['bairro' => 'Vila Presidente Vargas', 'preco' => ''],
            ['bairro' => 'Vila São Cristóvão', 'preco' => ''],
            ['bairro' => 'Vila São Cristóvão II', 'preco' => ''],
            ['bairro' => 'Vila São José', 'preco' => ''],
            ['bairro' => 'Vila São Vicente', 'preco' => ''],
            ['bairro' => 'Villaggio Di Fiori', 'preco' => ''],
            ['bairro' => 'Distrito de Baixa', 'preco' => ''],
            ['bairro' => 'Distrito de Ponte Alta', 'preco' => '']
        ]);
    }
}
